name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * *' # Run daily

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check for updates
        id: check-updates
        run: |
          npx npm-check-updates -u || exit 0

      - name: Commit and push updates
        if: steps.check-updates.outputs.exit-code == '0'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Update dependencies"
          git push
